baseURL = "https://blog.climbtw.com/"
# languageCode = "en-us"
languageCode = "zh-cn"
title = "Temple Blog"

theme = "hugo-theme-cleanwhite"

cleanDestinationDir = true
buildDrafts = false
buildFuture = true

hasCJKLanguage = true

[pagination]
  pagerSize = 10 # frontpage pagination

[markup]
  [markup.tableOfContents] 
    startLevel = 1 # 文章目录层级，无效，直接修改 footer.html 文件代码
    endLevel = 4
  [markup.highlight]
    style = "nord" # 代码块高亮，https://xyproto.github.io/splash/docs/all.html
    lineNos = true # 显示行号
    lineNumbersInTable = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # markdown 中使用 html

[[params.addtional_menus]]
title =  "READING"
href =  "/reading/"
[[params.addtional_menus]]
title =  "LIFE"
href =  "/life/"
[[params.addtional_menus]]
title =  "ARCHIVE"
href =  "/archive/"
[[params.addtional_menus]]
title =  "ABOUT"
href =  "/about/"

[params]
  header_image = "img/temple-home-bg.png"
  slogan = "山高自有客行路，水深自有渡船人"
  SEOTitle = "谌中钱的博客 | Temple Blog"
  description = ""
  keyword = ""

  image_404 = "img/temple-404-bg.png"
  title_404 = "页面不存在"

  upstreamAttribution = false # 显示主题作者信息
  omit_categories = false # 隐藏分类菜单

  # Sidebar settings
  sidebar_avatar = "img/temple.png"      # use absolute URL, seeing it's used in both `/` and `/about/`
  sidebar_about_description = "谌中钱（言戈，Temple Chan），男，29岁，177cm，76kg，摩羯座，汉族，中共团员，1996年1月14日出生于湖北省武汉市黄陂区，祖籍河南洛阳一带，始祖春秋时期郑国大夫裨谌。理学学士学位，主修计算机科学，中国内地不知名程序员，腾讯、Coupang、阿里高级搬砖人，爬界科技 创始人、首席执行官。"
  
  about_me = true
  bookmarks = true
  featured_tags = true 
  featured_condition_size = 0
  friends = true
  
  # Twikoo comments
  # Follow https://twikoo.js.org/ to set up your own env_id
  twikoo_env_id = "https://twikoo.climbtw.com/"



  # algolia site search
  algolia_search = false
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Artalk comments
  # Follow https://artalk.js.org/ to set up your own server
  artalk_enable = false
  artalk_server = "https://xxx.xxx.com"
  artalk_site = "xxx blog"

  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

  # leancloud storage for page view counter
  page_view_counter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # Baidu Analytics
  ba_track_id = ""

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = true 
  reward_guide = "您的咖啡能让我写出少 Bug 的代码 ☕️ ~"

  # Include any custom CSS and/or JS files, url or relative to /static folder
  #custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]



  [params.social]
  email          = "templechan@126.com"
  wechat         = "img/social/temple-social-wechat.png"
  # line         = "img/temple.png"
  telegram       = "img/social/temple-social-telegram.png"
  tiktok         = "https://www.douyin.com/user/MS4wLjABAAAA84o70K2c9LEZXJ9fHp0deVyvxMudni7rQgAahjtoWIX34SCg61Gbf6H4HYKneZsW"
  instagram     = "https://www.instagram.com/templechann"
  twitter       = "https://x.com/templechann"
  youtube       = "https://www.youtube.com/@templechann"
  zhihu           = "https://www.zhihu.com/people/templechan"
  weibo           = "https://weibo.com/u/7893774034"
  github         = "https://github.com/templechan"
  linkedin       = "https://www.linkedin.com/in/templechan"
  rss = true 

  # facebook      = "full profile url in facebook"
  # gitlab        = "full profile url in gitlab"
  # slack         = "full workspace url in slack" # 是一种用于办公的操作系统
  # stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid" # 一个与程序相关的IT技术问答网站

  # xing          = "https://www.xing.com/profile/yourxingid" # 德国类似Linkedin的职业社交网站
  # medium        = "full profile url in medium" # 一个网络文章发布平台，由推特联合创办人埃文·威廉姆斯和比兹·斯通于2012年8月创办
  # reddit        = "full profile url in reddit" # 一个美国著名的论坛，拥有庞大的用户群体和巨大的影响力
  # keybase       = "full profile url in keybase" # 基于PGP技术的社交网络平台
  # mastodon      = "full profile url in mastodon" # 一个自由开源的去中心化的分布式微博客社交网络
  # flickr = "full profile url for git user" # 雅虎旗下图片分享网站
  # pinterest = "full profile url in pinterest" # 以视觉方式发现创意点子的地方，比如食谱、家装等等

  [[params.bookmark_link]]
  title =  "爬界科技"
  href =  "https://climbtw.com"

  [[params.friend_link]]
  title = "谌中钱的博客"
  href =  "https://blog.climbtw.com"

[services]
  # Enable comments by entering your Disqus shortname
  [services.disqus]
    shortname = ""
  [services.googleAnalytics]
    id = ""

[outputs]
# home = ["HTML", "RSS", "Algolia"]
home = ["HTML", "RSS"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]